# Generated by Django 4.1.7 on 2023-04-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stages',
            options={'ordering': ['order'], 'verbose_name': 'этап работ', 'verbose_name_plural': 'этапы работ'},
        ),
    ]
