# Generated by Django 4.1.7 on 2023-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='team/', verbose_name='Фото'),
        ),
    ]
