# Generated by Django 4.1.7 on 2023-04-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtext',
            name='review_link',
            field=models.FileField(blank=True, max_length=1000, upload_to='reviews/', verbose_name='Ссылка на отзыв'),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='image',
            field=models.ImageField(max_length=500, upload_to='reviews-preview/', verbose_name='Превью отзыва'),
        ),
    ]
