# Generated by Django 4.1.7 on 2023-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок о компании',
                'verbose_name_plural': 'Блок о компании',
            },
        ),
        migrations.CreateModel(
            name='ContactsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок контактов',
                'verbose_name_plural': 'Блок контактов',
            },
        ),
        migrations.CreateModel(
            name='FooterBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок футера',
                'verbose_name_plural': 'Блок футера',
            },
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Навигационная панель',
                'verbose_name_plural': 'Навигационная панель',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Главный блок',
                'verbose_name_plural': 'Главный блок',
            },
        ),
        migrations.CreateModel(
            name='ProjectsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок проектов',
                'verbose_name_plural': 'Блок проектов',
            },
        ),
        migrations.CreateModel(
            name='QuestionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок часто задаваемых вопросов',
                'verbose_name_plural': 'Блок часто задаваемых вопросов',
            },
        ),
        migrations.CreateModel(
            name='ReviewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок отзывов клиентов',
                'verbose_name_plural': 'Блок отзывов клиентов',
            },
        ),
        migrations.CreateModel(
            name='ServicesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок услуг',
                'verbose_name_plural': 'Блок услуг',
            },
        ),
        migrations.CreateModel(
            name='StagesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок стадий работ',
                'verbose_name_plural': 'Блок стадий работ',
            },
        ),
        migrations.CreateModel(
            name='TeamBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок команды',
                'verbose_name_plural': 'Блок команды',
            },
        ),
        migrations.CreateModel(
            name='WarmingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блок прогрева',
                'verbose_name_plural': 'Блок прогрева',
            },
        ),
    ]
