# Generated by Django 4.1.7 on 2023-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_aboutblock_description_aboutblock_description_fifth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerblock',
            name='number',
            field=models.CharField(max_length=18, verbose_name='Номер компании'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='answer_fourth',
            field=models.TextField(verbose_name='Ответ №4'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='question_fourth',
            field=models.TextField(verbose_name='Вопрос №4'),
        ),
    ]
