# Generated by Django 4.1.7 on 2023-04-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_alter_headerblock_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerblock',
            name='logo',
            field=models.FileField(max_length=500, upload_to='header/', verbose_name='Лого'),
        ),
    ]
