# Generated by Django 4.1.7 on 2023-04-22 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_alter_headerblock_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutblock',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='description_fifth',
            field=ckeditor.fields.RichTextField(verbose_name='Описание №5'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='description_first',
            field=ckeditor.fields.RichTextField(verbose_name='Описание №1'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='description_fourth',
            field=ckeditor.fields.RichTextField(verbose_name='Описание №4'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='description_second',
            field=ckeditor.fields.RichTextField(verbose_name='Описание №2'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='description_sixth',
            field=ckeditor.fields.RichTextField(verbose_name='Описание №6'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='description_third',
            field=ckeditor.fields.RichTextField(verbose_name='Описание №3'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title_fifth',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №5'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title_first',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №1'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title_fourth',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №4'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title_second',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №2'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title_sixth',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №6'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title_third',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №3'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='address',
            field=ckeditor.fields.RichTextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='number',
            field=ckeditor.fields.RichTextField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='schedule',
            field=ckeditor.fields.RichTextField(verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='vk_link',
            field=ckeditor.fields.RichTextField(verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='projectsblock',
            name='title_first',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №1'),
        ),
        migrations.AlterField(
            model_name='projectsblock',
            name='title_forth',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №4'),
        ),
        migrations.AlterField(
            model_name='projectsblock',
            name='title_second',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №2'),
        ),
        migrations.AlterField(
            model_name='projectsblock',
            name='title_third',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №3'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='answer_fifth',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ №5'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='answer_first',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ №1'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='answer_fourth',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ №4'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='answer_second',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ №2'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='answer_third',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ №3'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='question_fifth',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос №5'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='question_first',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос №1'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='question_fourth',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос №4'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='question_second',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос №2'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='question_third',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос №3'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='title_first',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №1'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='title_second',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №2'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='title_third',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок №3'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='delivery_first',
            field=ckeditor.fields.RichTextField(verbose_name='Доставка №1'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='delivery_second',
            field=ckeditor.fields.RichTextField(verbose_name='Доставка №2'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_eighth',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №8'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_fifth',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №5'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_first',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №1'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_fourth',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №4'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_ninth',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №9'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_second',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №2'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_seventh',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №7'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_sixth',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №6'),
        ),
        migrations.AlterField(
            model_name='stagesblock',
            name='title_third',
            field=ckeditor.fields.RichTextField(verbose_name='Текст №3'),
        ),
        migrations.AlterField(
            model_name='teamblock',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teamblock',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='warmingblock',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок'),
        ),
    ]
