# Generated by Django 4.1.7 on 2023-04-22 16:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_alter_aboutblock_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('video_preview', models.ImageField(max_length=500, upload_to='warming/', verbose_name='Превью для видео')),
                ('image_one', models.ImageField(max_length=500, upload_to='warming/', verbose_name='Фото №1')),
                ('image_two', models.ImageField(max_length=500, upload_to='warming/', verbose_name='Фото №2')),
                ('image_three', models.ImageField(max_length=500, upload_to='warming/', verbose_name='Фото №3')),
            ],
            options={
                'verbose_name': 'Блок производства',
                'verbose_name_plural': 'Блок производства',
            },
        ),
        migrations.DeleteModel(
            name='WarmingBlock',
        ),
    ]
