# Generated by Django 4.1.7 on 2023-04-22 17:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_productionblock_delete_warmingblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsblock',
            name='image_forth',
        ),
        migrations.RemoveField(
            model_name='projectsblock',
            name='title_forth',
        ),
        migrations.RemoveField(
            model_name='projectsblock',
            name='video_link_forth',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='answer_fifth',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='answer_first',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='answer_fourth',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='answer_second',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='answer_third',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='question_fifth',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='question_first',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='question_fourth',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='question_second',
        ),
        migrations.RemoveField(
            model_name='questionsblock',
            name='question_third',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_eighth',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_fifth',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_first',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_fourth',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_ninth',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_second',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_seventh',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_sixth',
        ),
        migrations.RemoveField(
            model_name='stagesblock',
            name='title_third',
        ),
        migrations.RemoveField(
            model_name='teamblock',
            name='image_director',
        ),
        migrations.RemoveField(
            model_name='teamblock',
            name='image_manager',
        ),
        migrations.AddField(
            model_name='contactsblock',
            name='inst_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на инстаграм'),
        ),
        migrations.AddField(
            model_name='contactsblock',
            name='title',
            field=ckeditor.fields.RichTextField(default='Контакты', verbose_name='Заголовок блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionblock',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на видео'),
        ),
        migrations.AddField(
            model_name='projectsblock',
            name='title',
            field=ckeditor.fields.RichTextField(default='Реализованные проекты', verbose_name='Заголовок блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsblock',
            name='title',
            field=ckeditor.fields.RichTextField(default='Часто задаваемые вопросы', verbose_name='Заголовок блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewsblock',
            name='title',
            field=ckeditor.fields.RichTextField(default='Что о нас говорят наши клиенты', verbose_name='Заголовок блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesblock',
            name='title',
            field=ckeditor.fields.RichTextField(default='Возьмём на себя весь процесс изготовления мебели', verbose_name='Заголовок блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagesblock',
            name='delivery_title',
            field=ckeditor.fields.RichTextField(default='Доставка и оплата', verbose_name='Заголовок доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagesblock',
            name='title',
            field=ckeditor.fields.RichTextField(default='Этапы работы', verbose_name='Заголовок блока'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='vk_link',
            field=models.CharField(max_length=500, verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='footerblock',
            name='logo',
            field=models.FileField(max_length=500, upload_to='header/', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='footerblock',
            name='number',
            field=models.CharField(max_length=18, verbose_name='Номер компании'),
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='productionblock',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='image_first',
            field=models.FileField(max_length=500, upload_to='service/', verbose_name='Фото №1'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='image_second',
            field=models.FileField(max_length=500, upload_to='service/', verbose_name='Фото №2'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='image_third',
            field=models.FileField(max_length=500, upload_to='service/', verbose_name='Фото №3'),
        ),
        migrations.AlterField(
            model_name='teamblock',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок блока'),
        ),
    ]
