# Generated by Django 4.1.7 on 2023-04-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_remove_projectsblock_image_forth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesblock',
            name='image_first',
        ),
        migrations.RemoveField(
            model_name='servicesblock',
            name='image_second',
        ),
        migrations.RemoveField(
            model_name='servicesblock',
            name='image_third',
        ),
    ]
