# Generated by Django 4.1.7 on 2023-04-24 00:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_remove_servicesblock_image_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsblock',
            name='description_first',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Описание №1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsblock',
            name='description_second',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Описание №2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsblock',
            name='description_third',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Описание №3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectsblock',
            name='video_link_first',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на видео №1'),
        ),
        migrations.AlterField(
            model_name='projectsblock',
            name='video_link_second',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на видео №2'),
        ),
        migrations.AlterField(
            model_name='projectsblock',
            name='video_link_third',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на видео №3'),
        ),
    ]
