# Generated by Django 4.1.7 on 2024-01-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_projectsblock_description_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsblock',
            name='inst_link',
        ),
        migrations.AddField(
            model_name='contactsblock',
            name='instagram_link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='contactsblock',
            name='yandex_map_link',
            field=models.CharField(default='', max_length=500, verbose_name='Ссылка на Яндекс Карты'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес компании'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='instagram_link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='schedule',
            field=models.CharField(default='', max_length=255, verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='tg_link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='vk_link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на VK'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='whatsapp_link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на Whatsapp'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='yandex_map_link',
            field=models.CharField(default='', max_length=500, verbose_name='Ссылка на Яндекс Карты'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='number',
            field=models.CharField(max_length=18, verbose_name='Номер компании'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='schedule',
            field=models.CharField(default='', max_length=255, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='contactsblock',
            name='vk_link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на VK'),
        ),
    ]
