# Generated by Django 4.1.7 on 2023-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('number', models.CharField(max_length=40, verbose_name='Номер телефона')),
                ('message', models.TextField(blank=True, verbose_name='Какая мебель нужна?')),
                ('comfortable_time', models.CharField(blank=True, max_length=20, verbose_name='Какая мебель нужна?')),
                ('project_version', models.CharField(blank=True, max_length=10, verbose_name='Версия приложения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user_agent', models.CharField(blank=True, max_length=2000, verbose_name='UserAgent')),
                ('screen_resolution', models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана')),
                ('browser_language', models.CharField(blank=True, max_length=100, verbose_name='Язык браузера')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='Временная зона')),
                ('cookie', models.TextField(blank=True, max_length=5000, verbose_name='Cookie')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
