# Generated by Django 4.1.7 on 2023-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comfortable_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Удобное время'),
        ),
    ]
